### ISSUE TITLE
Installation issues on Windows 10 enterprise

### ISSUE THREAD

**Issue by ericle99** [royerlab/aydin#105]
**Describe the bug**
Hello Aydin Team. I have been trying to get Aydin to work on my labs processing station equipped with high end processor and GPU. I have been able to download and extract the Zip file without issue. However, when I try to run the Batch file, my terminal pops open for ~1s the first time after install and then for milliseconds on subsequent attempts at running the batch file. The terminal then closes itself and Aydin never opens. 

**To Reproduce**
1. download Aydin windows package 
2. extract all from zip file
3. open uncompressed folder
4. Click on run_aydin windows batch file (on Windows 10 enterprise) 

**Expected behavior**
Windows terminal opens for between 0 and 1 second before closing. Nothing occurs after

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Version 10.0.18362 Build 18362

**Additional context**

**Comment by AhmetCanSolak** [comment]
Thank you for the issue @ericleisten !

I will try to reproduce the error with the Windows bundle, meanwhile could you try installing Aydin with pip also? and let me know how it goes?

**Comment by ericleisten** [comment]
Hello!

I seem to also be having trouble with pip seen below. 

>>> pip install aydin
  File "<stdin>", line 1
    pip install aydin
        ^
SyntaxError: invalid syntax

**Comment by ericleisten** [comment]
No problem @AhmetCanSolak 

When trying with pip

">>> pip install aydin
  File "<stdin>", line 1
    pip install aydin
        ^
SyntaxError: invalid syntax"

**Comment by AhmetCanSolak** [comment]
I'm afraid you are missing `pip` on your system, could you check if you have a working `pip` installation first?

**Comment by AhmetCanSolak** [comment]
oh you run pip in python console, I just realized, could you try running `pip install aydin` on the commandline?

**Comment by ericleisten** [comment]
Got it. I tried to both run in command line and check for pip. Oddly it seems as if it is not recognizing python as installed at all? 

C:\Users\myuser>pip install aydin 
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\myuser>python -m pip --version
'python' is not recognized as an internal or external command,
operable program or batch file.

**Comment by AhmetCanSolak** [comment]
probably your python installation is not added to path. Please see: https://docs.python.org/3.9/using/windows.html#excursus-setting-environment-variables 

I am also looking into the bundle problem, will keep you posted.

**Comment by ericle99** [comment]
Hi Ahmet,

Over the weekend, I went ahead and updated my environment variables, and got Aydin installed using pip. 

However, I seem to still be having issues (post-computer reboot) when trying to call aydin in the command line. Below is the returned error message. 

>aydin
2022-02-15 14:34:45.110564: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-02-15 14:34:45.116851: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "C:\Users\edl0597\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\edl0597\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\edl0597\AppData\Local\Programs\Python\Python39\Scripts\aydin.exe\__main__.py", line 4, in <module>
  File "C:\Users\edl0597\AppData\Local\Programs\Python\Python39\lib\site-packages\aydin\__init__.py", line 5, in <module>
    from aydin.restoration.deconvolve.lr import lucyrichardson  # noqa: F401
  File "C:\Users\edl0597\AppData\Local\Programs\Python\Python39\lib\site-packages\aydin\restoration\deconvolve\lr.py", line 1, in <module>
    from aydin.it.deconvolution.lr_deconv_scipy import ImageTranslatorLRDeconvScipy
  File "C:\Users\edl0597\AppData\Local\Programs\Python\Python39\lib\site-packages\aydin\it\deconvolution\lr_deconv_scipy.py", line 4, in <module>
    from scipy.signal.signaltools import _init_freq_conv_axes, _apply_conv_mode
ImportError: cannot import name '_init_freq_conv_axes' from 'scipy.signal.signaltools' (C:\Users\edl0597\AppData\Local\Programs\Python\Python39\lib\site-packages\scipy\signal\signaltools.py)





Note: First error seems to deal with the GPU followed by a note to ignore if no GPU is present. The current workstation does contain a Quadro RTX 4000.

**Comment by AhmetCanSolak** [comment]
Hi @ericle99 ,

This is a problem occurred on our released versions when one of the dependencies we have got a breaking update. I fixed this on our latest master and next Aydin version will have the fix. For now you can do the following till I make a new Aydin version later this month:
`pip install aydin`
`pip install scipy=1.7.3`

PS: other warning is about cudatoolkit, once you run Aydin without problems we can also take care of the cudatoolkit problem :)

**Comment by AhmetCanSolak** [comment]
Glad to hear @ericle99 ! How did you install CUDA toolkit to your system? Installed with conda in an environment or made a system-wide installation with NVIDIA installer? 

PS: It can also help if you can share the output of `nvidia-smi` command on your systems with which cudatoolkit version you installed.

**Comment by ericle99** [comment]
Hi Ahmet

I was assume it was installed system wide with the NVIDIA installer. 

nvidia-smi returns 

Tue Feb 22 13:14:17 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 511.65       Driver Version: 511.65       CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 4000    WDDM  | 00000000:65:00.0  On |                  N/A |
| 30%   36C    P8    18W / 125W |    473MiB /  8192MiB |      2%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

**Comment by AhmetCanSolak** [comment]
Hi @ericle99 ! I did a bit research on this and I'm afraid your cudatoolkit version is not matching the cuda version supported by your driver. Could you check both for me please? and try to change their version if there is a mismatch?

Alternatively, you can try to install cudatoolkit within a conda environment as shown here: https://royerlab.github.io/aydin/getting_started/install.html#install-aydin-in-a-conda-environment-with-cuda-support 
Let me know how it goes if you give this a try also.

**Comment by AhmetCanSolak** [comment]
Happy new year @ericle99 ! I was wondering if everything is working right now. Please let me know if there is anything I can help with, otherwise I will be closing this issue.

**Comment by AhmetCanSolak** [comment]
I will close the issue @ericle99 , feel free to re-open if the same situation still occurs!
