### ISSUE TITLE
Significantly longer run times with certain test cases

### ISSUE THREAD

**Issue by AhmetCanSolak** [royerlab/aydin#115]
I started to observe some classic algorithm related tests started to take way too long to finish running. Particularly the following two: 

https://github.com/royerlab/aydin/blob/0f484cd6ec0fe05df06cf420fa4243db4c16eb49/aydin/it/classic_denoisers/test/test_harmonic.py#L10

https://github.com/royerlab/aydin/blob/0f484cd6ec0fe05df06cf420fa4243db4c16eb49/aydin/it/test/test_classic_saveload.py#L35

This PR will be closed once we merge a patch for these.

**Comment by royerloic** [comment]
this has been fixed

**Comment by AhmetCanSolak** [comment]
yes I can confirm this is addressed in #118 , thank you @royerloic !
