### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by mocherry** [royerlab/aydin#284]
Dear all,
I have tried to install Aydin.
When executing " pip install aydin",
I get the following error-message: 
File "C:\Users\kirsch\Miniconda3\envs\aydin_env\lib\site-packages\pip\_vendor\urllib3\response.py", line 442, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
WARNING: There was an error checking the latest version of pip.

Help would be greatly appreciated. Thanks and best,
Matthias

**Comment by AhmetCanSolak** [comment]
Hello @mocherry , thank you for the issue.

Could you upgrade your pip first with: `python -m pip install --upgrade pip`? 
Then try: `pip install aydin`? and please let me know if this solves the problem.

**Comment by AhmetCanSolak** [comment]
Happy new year @mocherry ! I am checking-in to see if upgrading your pip helped or not?

**Comment by mocherry** [comment]
Happy New Year as well.Yes, after doing this and a couple of other things, everything works.Best,MatthiasVon meinem/meiner Galaxy gesendet
-------- Ursprüngliche Nachricht --------Von: Ahmet Can Solak ***@***.***> Datum: 03.01.23  17:41  (GMT+01:00) An: royerlab/aydin ***@***.***> Cc: mocherry ***@***.***>, Mention ***@***.***> Betreff: Re: [royerlab/aydin] installation fails (Issue #284) 
Happy new year @mocherry ! I am checking-in to see if upgrading your pip helped or not?

**Comment by AhmetCanSolak** [comment]
Glad to hear that, I am closing this issue then. Feel free to reach out if you need help with Aydin in future!
