### ISSUE TITLE
Unable to load pre-trained model using the api

### ISSUE THREAD

**Issue by zacswider** [royerlab/aydin#300]
Hello,
I am trying to denoise a batch of images with a pre-trained FGR (CatBoost) model.

**To Reproduce**
```
from aydin.restoration.denoise.noise2selffgr import Noise2SelfFGR
from tifffile import imread

noisy_image_path = 'path/to/noisy_im.tif'
noisy_image = imread(noisy_image_path)
n2s = Noise2SelfFGR(variant = 'cb', use_model = True, input_model_path = "path/to/pretrained_model.zip")
denoised = n2s.denoise(noisy_image)
```

**Expected behavior**
I can run the equivalent command through the command line:

`aydin denoise *.tif --model-path=path/to/pretrained_model.zip --model-model`

and see that aydin quickly generates denoised images with the pretrained model.

**Screenshots**
![image](https://user-images.githubusercontent.com/51267747/220756933-b9992546-6d5a-4cc3-91cc-af41536fb5ed.png)

**Desktop (please complete the following information):**
 - The error repeats on both Ubuntu 22.04.2 LTS and Windows 11
 - Version:  aydin 0.10.15 installed with pip

**Additional context**
I tried installing the main github branch in a separate environment and the error persisted. 

This is amazing software, thank you to all the developers!

**Comment by AhmetCanSolak** [comment]
Hello @zacswider , thank you for the issue.

Unfortunately, some legacy parameters caused a confusion here. You will need to use the `load` method given here : https://royerlab.github.io/aydin//v0.1.15/api/restorations/denoise_restoration.html#aydin.restoration.denoise.noise2selffgr.Noise2SelfFGR.load
You will not need to pass any parameters while constructing `Noise2SelfFGR`

You can find code example for it here: https://github.com/royerlab/aydin/blob/9312f227605be26fce960373c1f29a71323da914/aydin/restoration/denoise/test/test_saveload.py#L58

Please let me know if this helps, I will be making a PR to clarify `Noise2SelfFGR` parameters.
Also, let me know if there is anything else I can help with. Thank you for using Aydin.

**Comment by zacswider** [comment]
Thanks for clarifying Ahmet! Everything is running smoothly now :)
