### ISSUE TITLE
Documentation refers to inexistent command "noise2self". CLI proposes "denoise".

### ISSUE THREAD

**Issue by tp81** [royerlab/aydin#44]
https://github.com/royerlab/aydin/blob/16b4d773dd5c3be3e837512a7f2b69cfe01c114f/tutorials/cli_tutorials.html#L143
https://github.com/royerlab/aydin/blob/16b4d773dd5c3be3e837512a7f2b69cfe01c114f/tutorials/cli_tutorials.html#L153
https://github.com/royerlab/aydin/blob/16b4d773dd5c3be3e837512a7f2b69cfe01c114f/tutorials/cli_tutorials.html#L162

**Comment by AhmetCanSolak** [comment]
hi @tp81 ! Thank you for the issue. Nice catch, obviously I forgot to update some of the commands in cli tutorials. Will be making an update shortly and will keep you posted.

**Comment by AhmetCanSolak** [comment]
I updated the docs @tp81 and will be closing this issue, feel free to re-open if you find out anything similar in the docs. Thanks again!
