### ISSUE TITLE
aydin_0.1.11_linux.zip needs glibc >= 2.18

### ISSUE THREAD

**Issue by truatpasteurdotfr** [royerlab/aydin#58]
**Describe the bug**
The linux bundled version is not compatible with CentOS-7 x86_64. Missing documentation requirement...

**To Reproduce**
1.  wget https://github.com/royerlab/aydin/releases/download/v0.1.11/aydin_0.1.11_linux.zip
2.  unzip  aydin_0.1.11_linux.zip
3. cd aydin_0.1.11_linux/
4. ./run_aydin.sh

**Expected behavior**
aydin starting as explained https://royerlab.github.io/aydin/getting_started/install.html#install-aydin-bundle-on-linux

**Screenshots**

```
[tru@sillage aydin_0.1.11_linux]$ ./run_aydin.sh 
Traceback (most recent call last):
  File "build/linux/runtimehooks/hook-splash.py", line 1, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "matplotlib/__init__.py", line 107, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "matplotlib/rcsetup.py", line 26, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "matplotlib/colors.py", line 82, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "matplotlib/scale.py", line 18, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "matplotlib/ticker.py", line 179, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 546, in exec_module
  File "matplotlib/transforms.py", line 46, in <module>
ImportError: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /dev/shm/aydin_0.1.11_linux/aydin/libstdc++.so.6)
[13014] Failed to execute script 'hook-splash' due to unhandled exception!
```
**Desktop (please complete the following information):**
 - OS:  CentOS-7 x86_64 (up to date)
 - Version: 7.9.2009

**Additional context**
```
[tru@sillage aydin_0.1.11_linux]$ rpm -q glibc
glibc-2.17-325.el7_9.x86_64
glibc-2.17-325.el7_9.i686
```

**Comment by AhmetCanSolak** [comment]
Hello @truatpasteurdotfr ! Thanks for the issue.

Our linux bundle is built on Ubuntu 18.04 which comes with `glibc 2.27` to the best of my knowledge. We do not have the bandwidth to build more variety of bundles for different linux distros at this point but would welcome any contribution. If you would like to start building bundles for CentOS for example? Let me know.

Also I am curious if glibc version would be a problem at all if you go with `pip install aydin`, let me know if you give it a try.

**Comment by truatpasteurdotfr** [comment]
Hi @AhmetCanSolak 

No worries, I would just add the info on your build environment so that the people using your bundle are not surprised.
For portability issue, I would move the burden into conda. I will install a python3.9 version from source and try the pip install method.
I will make a PR for a docker/singularity container :P

**Comment by truatpasteurdotfr** [comment]
from a source compiled python-3.9.9, the `pip install aydin` works out of the box, one only needs to loal the cuda >=11.0 version to provide gpu support.
```
[tru@sillage ~]$ source ~/virtualenv/Python-3.9.9/aydin_env/bin/a
activate          activate.fish     activate.ps1      aydin
activate.csh      activate.nu       activate_this.py
[tru@sillage ~]$ source ~/virtualenv/Python-3.9.9/aydin_env/bin/activate
(aydin_env) [tru@sillage ~]$ aydin
2021-11-30 13:32:45.075655: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /c7/shared/Python/3.9.9/lib
2021-11-30 13:32:45.075690: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
(aydin_env) [tru@sillage ~]$ module av cuda

---------------------------- /c7/shared/modulefiles ----------------------------
cuda/10.0.130_410.48    cuda/11.2.1_460.32.03   cuda/7.5.18
cuda/10.1.105_418.39    cuda/11.2.2_460.32.03   cuda/8.0.44
cuda/10.1.168_418.67    cuda/11.3.0_465.19.01   cuda/8.0.61.2
cuda/10.1.243_418.87.00 cuda/11.3.1_465.19.01   cuda/9.0.176_384.81
cuda/10.2.89_440.33.01  cuda/11.4.0_470.42.01   cuda/9.1.85_387.26
cuda/11.0.2_450.51.05   cuda/6.5.14             cuda/9.1.85_387.261
cuda/11.0.3_450.51.06   cuda/6.5.19             cuda/9.2.148_396.37
cuda/11.1.0_455.23.05   cuda/7.0.28             cuda/9.2.88_396.26
(aydin_env) [tru@sillage ~]$ module add cuda/11.4.0_470.42.01
(aydin_env) [tru@sillage ~]$ aydin
WARNING: CPU random generator seem to be failing, disabling hardware random number generation
WARNING: RDRND generated: 0xffffffff 0xffffffff 0xffffffff 0xffffffff
```
(ignore the warning, known issue on AMD Ryzen on CentOS-7)

**Comment by truatpasteurdotfr** [comment]
I am not sure why the gpu seems unused (with `nvidia-smi dmon` running) while doing:
- Load examples: Gauss
- Start

**Comment by truatpasteurdotfr** [comment]
easier to see the gpu running from the command line!
```
wget 'https://drive.google.com/uc?id=17e_ECJA7DUQGu9JELbTkAKbOVVE9olHN' -O Gauss_noisy.png
aydin denoise Gauss_noisy.png
```
and watch `nvidia-smi dmon` in another window!
- python 3.9.9 + pip install aydin works fine from CentOS-7
- miniconda3 container singularity based also works
