### ISSUE TITLE
Changing the default save location

### ISSUE THREAD

**Issue by AhmetCanSolak** [royerlab/aydin#91]
**Is your feature request related to a problem? Please describe.**
There are some users giving us feedback that default save location is making their life harder sometimes. I can understand it would be useful to see all resulting images and models etc in one folder sometimes. Currently, we are writing the resulting images/models all next to the input image in the file system. This behavior is same for all operating systems we run on.

**Describe the solution you'd like**
I believe ultimate solution would be being able to specific the output paths on all interfaces of Aydin which is currently work in progress (see #85 and #84). Also, default location should be adjusted if needed.

**Describe alternatives you've considered**
- Saving all resulting files(images/models/etc) next to the input image in file system :rocket: 
- Saving everything in a 'denoised/result' folder next to the input image in the file system :tada: 
- Your ideas?

Feel free to react with the emojis accordingly and we can use that as a poll.

**Comment by li-li-github** [comment]
I think "Saving all resulting files(images/models/etc) next to the input image in file system" can stay as the default setting. 
It could be convenient to have the possibility to choose the output location, particularly in the case of batch processing.

**Comment by AhmetCanSolak** [comment]
right now we have possibility to choose output location both on Aydin CLI and Aydin Studio and we seem to be happy with current default location. I will close this issue for now but anyone can re-open later if further discussion needed on this.
